-- Seed: lookups + the Pre-Anesthesia Assessment layout (published v1).
-- Idempotent: skips if the layout already exists.

INSERT INTO lookup_item (lookup_key, value, label, parent_key, sort_order) VALUES
  -- procedure categories (cascade parents)
  ('procedureCategories','general','General Surgery',NULL,10),
  ('procedureCategories','ortho','Orthopedics',NULL,20),
  ('procedureCategories','ent','ENT',NULL,30),
  ('procedureCategories','gi','Gastroenterology',NULL,40),
  -- procedures, cascading on category value
  ('procedures','lap-chole','Laparoscopic Cholecystectomy','general',10),
  ('procedures','open-appy','Open Appendectomy','general',20),
  ('procedures','hernia-repair','Inguinal Hernia Repair','general',30),
  ('procedures','mastectomy','Mastectomy','general',40),
  ('procedures','thyroidectomy','Thyroidectomy','general',50),
  ('procedures','tka','Total Knee Arthroplasty','ortho',10),
  ('procedures','tha','Total Hip Arthroplasty','ortho',20),
  ('procedures','acl-recon','ACL Reconstruction','ortho',30),
  ('procedures','shoulder-arthro','Shoulder Arthroscopy','ortho',40),
  ('procedures','orif-ankle','ORIF Ankle','ortho',50),
  ('procedures','carpal-tunnel','Carpal Tunnel Release','ortho',60),
  ('procedures','tonsillectomy','Tonsillectomy','ent',10),
  ('procedures','septoplasty','Septoplasty','ent',20),
  ('procedures','fess','Functional Endoscopic Sinus Surgery','ent',30),
  ('procedures','myringotomy','Myringotomy with Tubes','ent',40),
  ('procedures','thyroplasty','Thyroplasty','ent',50),
  ('procedures','egd','Upper Endoscopy (EGD)','gi',10),
  ('procedures','colonoscopy','Colonoscopy','gi',20),
  ('procedures','ercp','ERCP','gi',30),
  ('procedures','peg-tube','PEG Tube Placement','gi',40),
  ('procedures','sigmoidoscopy','Flexible Sigmoidoscopy','gi',50),
  -- allergies
  ('allergies','nkda','NKDA (No Known Drug Allergies)',NULL,0),
  ('allergies','penicillin','Penicillin',NULL,10),
  ('allergies','sulfa','Sulfa Drugs',NULL,20),
  ('allergies','latex','Latex',NULL,30),
  ('allergies','morphine','Morphine',NULL,40),
  ('allergies','codeine','Codeine',NULL,50),
  ('allergies','aspirin','Aspirin',NULL,60),
  ('allergies','iodine','Iodine / Contrast',NULL,70),
  ('allergies','eggs','Eggs (Propofol caution)',NULL,80),
  ('allergies','succinylcholine','Succinylcholine',NULL,90),
  ('allergies','other','Other',NULL,100),
  -- comorbidities
  ('comorbidities','htn','Hypertension',NULL,10),
  ('comorbidities','dm2','Diabetes Mellitus Type 2',NULL,20),
  ('comorbidities','cad','Coronary Artery Disease',NULL,30),
  ('comorbidities','copd','COPD',NULL,40),
  ('comorbidities','asthma','Asthma',NULL,50),
  ('comorbidities','osa','Obstructive Sleep Apnea',NULL,60),
  ('comorbidities','ckd','Chronic Kidney Disease',NULL,70),
  ('comorbidities','gerd','GERD',NULL,80),
  ('comorbidities','afib','Atrial Fibrillation',NULL,90),
  ('comorbidities','hypothyroid','Hypothyroidism',NULL,100)
ON CONFLICT (lookup_key, value) DO NOTHING;

INSERT INTO form_layout (layout_key, version, status, json, published_at)
SELECT 'pre-anesthesia-assessment', 1, 'published', $j$
{
  "title": "Pre-Anesthesia Assessment",
  "fields": [
    {"name":"patientName","label":"Patient Name","controlType":"text","dataType":"string","required":true,"group":"patient","order":10,
     "aliases":["patient","name","patient name"]},
    {"name":"dob","label":"Date of Birth","controlType":"date","dataType":"date","required":true,"max":"today","group":"patient","order":20,
     "aliases":["DOB","date of birth","born"]},
    {"name":"heightCm","label":"Height","controlType":"number","dataType":"number","unit":"cm","min":30,"max":250,"group":"patient","order":30,
     "aliases":["height"]},
    {"name":"weightKg","label":"Weight","controlType":"number","dataType":"number","unit":"kg","min":1,"max":400,"group":"patient","order":40,
     "aliases":["weight"]},
    {"name":"bmi","label":"BMI","controlType":"number","dataType":"number","group":"patient","order":50,
     "computedFrom":{"fn":"bmi","inputs":["heightCm","weightKg"]}},
    {"name":"asaClass","label":"ASA Classification","controlType":"radio","dataType":"string","required":true,"group":"assessment","order":10,
     "options":{"inline":[{"value":"1","label":"ASA I"},{"value":"2","label":"ASA II"},{"value":"3","label":"ASA III"},{"value":"4","label":"ASA IV"}]},
     "aliases":["ASA","ASA class","physical status"]},
    {"name":"mallampati","label":"Mallampati Score","controlType":"dropdown","dataType":"string","group":"airway","order":10,
     "options":{"inline":[{"value":"1","label":"Class I"},{"value":"2","label":"Class II"},{"value":"3","label":"Class III"},{"value":"4","label":"Class IV"}]},
     "aliases":["mallampati","mallampati class","mallampati score"]},
    {"name":"bp","label":"Blood Pressure","controlType":"bpPair","dataType":"bpPair","group":"assessment","order":20,
     "bpBounds":{"sysMin":60,"sysMax":260,"diaMin":30,"diaMax":160},
     "aliases":["blood pressure","BP","pressure"]},
    {"name":"heartRate","label":"Heart Rate","controlType":"number","dataType":"number","unit":"bpm","min":20,"max":250,"group":"assessment","order":30,
     "aliases":["heart rate","pulse","HR"]},
    {"name":"allergies","label":"Allergies","controlType":"multiselect","dataType":"string[]","group":"assessment","order":40,
     "options":{"lookupKey":"allergies"},
     "aliases":["allergy","allergies","allergic to"]},
    {"name":"allergyOther","label":"Other Allergy (specify)","controlType":"text","dataType":"string","group":"assessment","order":50,
     "visibleWhen":{"field":"allergies","op":"contains","value":"other"},
     "aliases":["other allergy"]},
    {"name":"npoTime","label":"NPO Since","controlType":"time","dataType":"time","required":true,"group":"assessment","order":60,
     "aliases":["NPO","NPO time","nothing by mouth","fasting since"]},
    {"name":"comorbidities","label":"Comorbidities","controlType":"checkboxGroup","dataType":"string[]","group":"assessment","order":70,
     "options":{"lookupKey":"comorbidities"},
     "aliases":["comorbidities","medical history","conditions"]},
    {"name":"smoker","label":"Smoking Status","controlType":"radio","dataType":"string","group":"assessment","order":80,
     "options":{"inline":[{"value":"yes","label":"Yes"},{"value":"no","label":"No"},{"value":"former","label":"Former"}]},
     "aliases":["smoker","smoking","smoking status","tobacco"]},
    {"name":"packYears","label":"Pack Years","controlType":"number","dataType":"number","min":0,"max":200,"group":"assessment","order":90,
     "visibleWhen":{"field":"smoker","op":"in","value":["yes","former"]},
     "requiredWhen":{"field":"smoker","op":"eq","value":"yes"},
     "aliases":["pack years"]},
    {"name":"procedureCategory","label":"Procedure Category","controlType":"dropdown","dataType":"string","required":true,"group":"procedure","order":10,
     "options":{"lookupKey":"procedureCategories"},
     "aliases":["category","procedure category","specialty"]},
    {"name":"procedure","label":"Procedure","controlType":"dropdown","dataType":"string","required":true,"group":"procedure","order":20,
     "options":{"lookupKey":"procedures"},"filterBy":"procedureCategory",
     "aliases":["procedure","operation","surgery"]},
    {"name":"procedureTime","label":"Procedure Time","controlType":"time","dataType":"time","required":true,"group":"procedure","order":30,
     "aliases":["procedure time","surgery time","scheduled for"]},
    {"name":"airwayNotes","label":"Airway Notes","controlType":"textarea","dataType":"string","group":"airway","order":20,
     "aliases":["airway","airway notes"]},
    {"name":"consentVerified","label":"Consent Verified","controlType":"checkbox","dataType":"boolean","mustBeTrue":true,"group":"procedure","order":40,
     "aliases":["consent","consent verified"]}
  ],
  "crossFieldRules": [
    {"id":"npo-before-procedure",
     "message":"NPO time must be before procedure time",
     "condition":{"field":"npoTime","op":"lt","valueFromField":"procedureTime"}}
  ]
}
$j$::jsonb, now()
WHERE NOT EXISTS (SELECT 1 FROM form_layout WHERE layout_key = 'pre-anesthesia-assessment');
